application: eco-theater-682
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /$
  script: main.application
- url: /guestbook.*
  script: guestbook.application
- url: /store.*
  script: store.application
- url: /test.*
  script: test.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"